##############################
### SCREENSHOT KEYBINDINGS ###
##############################

# Screenshot - Full Screen (save to file)
bind = , Print, exec, sh -c 'grimblast --notify save screen ~/Pictures/Screenshots/$(date +"screenshot_%Y-%m-%d-%H%M%S.%3N.png")'

# Screenshot - Select Area (save to file)
bind = SHIFT, Print, exec, sh -c 'grimblast --notify save area ~/Pictures/Screenshots/$(date +"screenshot_%Y-%m-%d-%H%M%S.%3N.png")'

# Screenshot - Active Window (save to file)
bind = ALT, Print, exec, sh -c 'grimblast --notify save active ~/Pictures/Screenshots/$(date +"screenshot_%Y-%m-%d-%H%M%S.%3N.png")'

# Screenshot - Select Window (save to file)
bind = SHIFT ALT, Print, exec, sh -c 'grimblast --notify save window ~/Pictures/Screenshots/$(date +"screenshot_%Y-%m-%d-%H%M%S.%3N.png")'

# Screenshot - Full Screen (copy to clipboard)
bind = CTRL, Print, exec, grimblast --notify copy screen

# Screenshot - Select Area (copy to clipboard)
bind = CTRL SHIFT, Print, exec, grimblast --notify copy area

# Screenshot - Active Window (copy to clipboard)
bind = CTRL ALT, Print, exec, grimblast --notify copy active

# Screenshot - Select Window (copy to clipboard)
bind = CTRL SHIFT ALT, Print, exec, grimblast --notify copy window
